import { app, BrowserWindow, session } from 'electron'
import path from 'path'
import fs from 'fs'
import { setCookiesPath } from './ytdlp'

let loginWindow: BrowserWindow | null = null

/**
 * 打开 YouTube 登录窗口；关闭后从登录分区导出 youtube/google cookie
 * 为 Netscape cookies.txt，同步到 ytdlp 缓存，并通过回调通知调用方。
 */
export function openYoutubeLoginWindow(onExported: (cookiesFilePath: string) => void): void {
  // 已经打开则聚焦，不重复创建
  if (loginWindow && !loginWindow.isDestroyed()) {
    loginWindow.focus()
    return
  }

  loginWindow = new BrowserWindow({
    width: 900,
    height: 700,
    title: '登录 YouTube',
    autoHideMenuBar: true,
    webPreferences: {
      partition: 'persist:youtube-login',
      contextIsolation: true,
      nodeIntegration: false,
    },
  })

  loginWindow.loadURL('https://accounts.google.com/signin/v2/identifier?service=youtube')

  // 登录成功后 Google 会跳转到 youtube.com，等 2 秒让 cookie 落地后自动关窗
  loginWindow.webContents.on('did-navigate', (_e, url) => {
    if (url.includes('youtube.com') && !url.includes('accounts.google.com')) {
      setTimeout(() => {
        if (loginWindow && !loginWindow.isDestroyed()) loginWindow.close()
      }, 2000)
    }
  })

  loginWindow.on('closed', async () => {
    loginWindow = null
    try {
      const cookiesFilePath = await exportYoutubeCookies()
      // 同步到主进程 ytdlp 缓存 + 通知调用方更新 settings
      setCookiesPath(cookiesFilePath)
      onExported(cookiesFilePath)
    } catch (err) {
      console.error('[login] cookie export failed:', err)
    }
  })
}

/** 从登录分区导出 youtube/google cookie 为 Netscape cookies.txt，返回文件路径 */
async function exportYoutubeCookies(): Promise<string> {
  const loginSession = session.fromPartition('persist:youtube-login')
  const cookies = await loginSession.cookies.get({})

  // 只保留 youtube / google 相关 cookie
  const targetCookies = cookies.filter((c) => {
    const d = (c.domain || '').toLowerCase()
    return d.includes('youtube.com') || d.includes('google.com')
  })

  // Netscape cookies.txt 格式：
  // domain \t include_subdomains \t path \t secure \t expiry \t name \t value
  const lines: string[] = [
    '# Netscape HTTP Cookie File',
    '# Generated by VideoDownloader',
    '',
  ]
  for (const c of targetCookies) {
    const domain = c.domain || ''
    const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const cookiePath = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0
    lines.push(`${domain}\t${includeSub}\t${cookiePath}\t${secure}\t${expiry}\t${c.name}\t${c.value}`)
  }

  const cookiesFilePath = path.join(app.getPath('userData'), 'youtube-cookies.txt')
  fs.writeFileSync(cookiesFilePath, lines.join('\n'), 'utf-8')
  console.log(`[login] exported ${targetCookies.length} cookies → ${cookiesFilePath}`)
  return cookiesFilePath
}
